image: node

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm install browserify
  artifacts:
    paths:
      - build

# test:
#   stage: test
#   cache:
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - npm run test

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - npm run package
  artifacts:
    paths:
      - build
  only:
    - master
  publish: build
